import Head from 'next/head';
import { useEffect, useState } from 'react';

import { Cabecalho } from '../../components/Cabecalho';
import { CardLivros } from '../../components/Card-livros';
import { Footer } from '../../components/footer';
import api from '../../services/api';

export default function Home() {
  const [livros, setLivros] = useState([]);
  useEffect(() => {
    api
      .get('/livros')
      .then((response) => {
        setLivros(response.data);
      })
      .catch((err) => {
        console.log('Deu ruim: ', err);
      });
  }, []);
  return (
    <div className="grid grid-cols-6 grid-rows-6">
      <Cabecalho />

      {livros.map((livro) => {
        return (
          <div key={livro.id}>
            <CardLivros
              id={livro.id}
              titulo={livro.titulo}
              autor={livro.autor}
              editora={livro.editora}
              data={livro.data_publicacao}
              preco={livro.preco}
            />
          </div>
        );
      })}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Footer />
    </div>
  );
}
