import Head from 'next/head';
import { useEffect, useState } from 'react';

import { Cabecalho } from '../components/Cabecalho';
import { Card } from '../components/Card';
import { Footer } from '../components/footer';
import api from './../services/api';

export default function Home() {
  const [autores, setAutores] = useState([]);
  useEffect(() => {
    api
      .get('/')
      .then((response) => {
        setAutores(response.data);
      })
      .catch((err) => {
        console.log('Deu ruim: ', err);
      });
  }, []);
  return (
    <div className="grid grid-cols-6 grid-rows-6">
      <Cabecalho />

      {autores.map((autor) => {
        return (
          <div key={autor.id}>
            <Card
              id={autor.id}
              nome={autor.nome}
              sobrenome={autor.sobrenome}
              data={autor.data_nascimento}
            />
          </div>
        );
      })}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Footer />
    </div>
  );
}
