import Head from 'next/head'
import Footer from '../../components/footer'
import Cabecalho from '../../components/Cabecalho.js'
import api from '../api/api.js'
import CardLivros from '../../components/Card-livros'
import { useEffect,useState } from 'react'


export default function Home() {
  
	const [livros, setLivros] = useState([])
  useEffect(() => {
		api.get('/livros')
			.then(response => {
				setLivros(response.data)
			})
			.catch(err => {
				console.log('Deu ruim: ', err)
			})
	}, [])
  return (
    <div className="grid grid-cols-6 grid-rows-6">
      <Cabecalho/>

    {
				livros.map(livro => {
  
					return (
						<div key={livro.id}>
							<CardLivros id={livro.id} titulo={livro.titulo} autor={livro.autor} editora={livro.editora} data={livro.data_publicacao} preco={livro.preco}/>
              
						</div>
					)
				})
			}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Footer/>
    </div>
  )
}
