import Head from 'next/head'
import Footer from '../components/footer.js'
import Cabecalho from '../components/Cabecalho.js'
import api from './api/api'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'
import { useEffect,useState } from 'react'


export default function Home() {
  
	const [autores, setAutores] = useState([])
  useEffect(() => {
		api.get('/')
			.then(response => {
				setAutores(response.data)
			})
			.catch(err => {
				console.log('Deu ruim: ', err)
			})
	}, [])
  return (
    <div>
      <Cabecalho/>

    {
				autores.map(autor => {
  
					return (
						<div >
							<Card id={autor.id} nome={autor.nome} sobrenome={autor.sobrenome} data={autor.data_nascimento}/>
              
						</div>
					)
				})
			}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Footer/>
    </div>
  )
}
